### Health Check
GET http://localhost:9999/



### Register User
POST http://localhost:9999/register
Content-Type: application/json

{
    "name": "jhon doe",
    "email": "jd@gmail.com",
    "password": "123456",
    "username": "jhon_doe"
}

### Login User
POST http://localhost:9999/login
Content-Type: application/json

{
    "email": "jd@gmail.com",
    "password": "123456"
}

###
GET http://localhost:9999/get_user_and_profile
Content-Type: application/json

{
    "token": "095d9aeead11e900f410b0f977953295802d05d4fa6fc33b19c5d2778b34359f"
}

###update user profile
POST http://localhost:9999/update_profile_data
Content-Type: application/json

{
    "token": "fb9236bdbba25f2086dc7263a860a228e605b833c15ef7afbaedff62c87fd17f",
    "bio": "Software Engineer",
    "currentPost": "CTO",
    "pastWork":[
        {
            "company": "Google",
            "position": "CTO",
            "years": "2+"
        }
    ],
    "education": [
        {
            "school": "GIT",
            "degree": "B.Tech",
            "fieldOfStudy": "2007-2011"
        }
    ]
}


###
GET http://localhost:9999/posts


###Deleting post
POST http://localhost:9999/delete_post
Content-Type: application/json

{
    "token": "2e32b287fb9e62e7b4349a5a324041c1d49f97b19c76a63a62634206e2ea0e60",
    "postId": "6a71cbf454864f76167d5318"
}
