### Health Check
GET http://localhost:9999/



### Register User
POST http://localhost:9999/register
Content-Type: application/json

{
    "name": "jhon doe",
    "email": "jd@gmail.com",
    "password": "123456",
    "username": "jhon_doe"
}

### Login User
POST http://localhost:9999/login
Content-Type: application/json

{
    "email": "jd@gmail.com",
    "password": "123456"
}

###
GET http://localhost:9999/get_user_and_profile
Content-Type: application/json

{
    "token": "d063fa88078a148d069524e88b3f35ca3bfe2f8b6292a0e6a7df03dcb3603cdf"
}

###update user profile
POST http://localhost:9999/update_profile_data
Content-Type: application/json

{
    "token": "8b891e53eed7aee520d985a5de19d588e93c23d527d600a6a85c787e289fe873",
    "bio": "Software Engineer",
    "currentPost": "CTO",
    "pastWork":[
        {
            "company": "Microsoft",
            "position": "CTO",
            "years": "2+"
        }
    ],
    "education": [
        {
            "school": "IIT",
            "degree": "B.Tech",
            "fieldOfStudy": "2007-2011"
        }
    ]
}


###
GET http://localhost:9999/posts

